# Configuration file for training LightDepthNet

# Data settings
data_root: data/nyu  # Path to NYU Depth v2 dataset
img_height: 480      # Output and preprocessed image height (pixels)
img_width: 640       # Output and preprocessed image width (pixels)

# Training settings
batch_size: 32       # Batch size for training
num_epochs: 50       # Number of training epochs
learning_rate: 0.0001  # Learning rate (1e-4)

# System settings
num_workers: 4       # Number of dataloader workers
device: cuda         # Device: 'cuda' or 'cpu'

# Resume training 
resume_from: null  # Path to checkpoint to resume from, or null to start fresh

checkpoint_frequency: 5  # Save checkpoint every 5 epochs (set to 0 to disable)
